# Generated by Django 5.1.1 on 2024-09-09 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(default='Sin contenido'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
